apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-pv-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # Permite que múltiples pods lo usen simultáneamente
  nfs:
    server: 172.31.17.121  # IP privada de k8smaster0
    path: /mnt/nfs-filemanager
  storageClassName: nfs